// Generated by CoffeeScript 1.10.0
(function() {
  var fetch;

  fetch = require('node-fetch');

  module.exports = function(callback) {
    var ref, tags, tagsJson;
    tagsJson = (ref = process.env.BBN_ENTRIES_TAGS) != null ? ref : '[]';
    tags = JSON.parse(tagsJson);
    return fetch('http://blog.bouzuya.net/posts.json').then(function(res) {
      return res.json();
    }).then(function(posts) {
      var year;
      year = new Date(new Date().getTime() - 24 * 60 * 60 * 1000).getYear() + 1900;
      return posts.filter(function(i) {
        return i.pubdate.match(new RegExp('^' + year));
      });
    }).then(function(posts) {
      return tags.map(function(tag) {
        return {
          tag: tag,
          count: posts.filter(function(i) {
            return i.tags.some(function(j) {
              return j === tag;
            });
          }).length
        };
      }).concat({
        tag: 'all',
        count: posts.length
      });
    }).then(function(counts) {
      var result;
      result = {};
      counts.forEach(function(arg) {
        var count, tag;
        tag = arg.tag, count = arg.count;
        return result['bbn-entries-' + tag.replace(/ /g, '-')] = count;
      });
      return result;
    }).then((function(result) {
      return callback(null, result);
    }), callback);
  };

}).call(this);
